# Generated by Django 4.2.3 on 2023-08-12 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_userprofile_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mobile_no',
            field=models.CharField(max_length=10),
        ),
    ]
