# Generated by Django 4.2.3 on 2023-08-12 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_bookings_user_alter_reviews_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0003_alter_userprofile_mobile_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwallet',
            name='account_no',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='userwallet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
