# Generated by Django 4.2.3 on 2023-08-18 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_remove_hotel_image_hotelimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='hotelimage',
            field=models.ImageField(null=True, upload_to='hotels/'),
        ),
        migrations.AlterField(
            model_name='hotelimage',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stay', to='booking.hotel'),
        ),
    ]
